server:
  port: 8082
  error:
    include-message: always
spring:
  application:
    name: product-service
  cloud:
    config:
      uri: http://localhost:8081
      username: root
      password: s3cr3t
  boot:
    admin:
      client:
        url: http://localhost:8086
  datasource:
    url: jdbc:h2:file:./test_db;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=FALSE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    initialization-mode: always
    platform: h2
    username: sa
    password:
  jpa:
     database-platform: org.hibernate.dialect.H2Dialect
     defer-datasource-initialization: true
     hibernate:
       ddl-auto: create
  h2:
     console:
       enabled: true
       path: /h2-console